fixtures:
  symlinks:
    nginx: "#{source_dir}"
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  forge_modules:
    java:
      repo: "puppetlabs/java"
      ref: "3.0.0"
    nginx:
      repo: "puppet/nginx"
      ref: "1.0.0"
