image: "ruby:2.5"

stages:
  - install
  - test

cache:
  paths:
    - vendor/ruby
    - spec/fixtures
    - Gemfile.lock

prepare:
  stage: install
  tags:
    - docker-runner
  script:
    - gem install bundler -v 2.0.2
    - bundle install --jobs $(nproc)
    - bundle install --jobs $(nproc) --deployment


test-validate:
  stage: test
  tags:
    - docker-runner
  script:
    - gem install bundler -v 2.0.2
    - bundle install --deployment
    - bundle exec rake validate

test-lint:
  stage: test
  tags:
    - docker-runner
  script:
    - gem install bundler -v 2.0.2
    - bundle install --deployment
    - bundle exec rake lint

test-rspec:
  stage: test
  tags:
    - docker-runner
  script:
    - gem install bundler -v 2.0.2
    - bundle install --deployment
    - bundle exec rake spec
  coverage: '/Resource coverage: \d+\.\d+/'
